import { FiCode, FiFileText, FiImage } from 'react-icons/fi';

const Artifact = () => {
    return (
        <div className='flex flex-1 flex-col'>
            {/* Header */}
            <div className='flex flex-none items-center border-b px-5 py-3.5 border-[var(--app-border)]'>
                <p className='text-sm font-medium text-[var(--text)]'>Artifact</p>
            </div>

            {/* Empty state */}
            <div className='flex flex-1 flex-col items-center justify-center gap-5 px-6 text-center'>
                <div className='flex gap-3'>
                    {[FiCode, FiFileText, FiImage].map((Icon, i) => (
                        <div
                            key={i}
                            className='flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--icon-bg)] text-[var(--icon-text)]'
                        >
                            <Icon size={16} />
                        </div>
                    ))}
                </div>
                <div>
                    <p className='text-sm font-medium text-[var(--text-heading)]'>No artifact yet</p>
                    <p className='mt-1.5 text-[12px] leading-5 text-[var(--text-muted)]'>
                        Code, documents, and other outputs<br />generated by Friday will appear here.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default Artifact;
